package Sphere::Model::SphereAppDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Sphere::Schema::SphereAppDB',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=sphere_application_database',
        user => 'sphere_application_administrator',
        password => 'password',
    }
);

=head1 NAME

Sphere::Model::SphereAppDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Sphere>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Sphere::Schema::SphereAppDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
